{
 "title": "RTE Energies",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "CONSO PAYS",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "targets": [
    { "expr": "rte_consommation", "legendFormat": "Consommation" }
   ]
  },
  {
   "title": "PRODUCTION",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "targets": [
    { "expr": "rte_fioul", "legendFormat": "Fioul" },
    { "expr": "rte_bioenergies", "legendFormat": "Bio energies" },
    { "expr": "rte_nucleaire", "legendFormat": "Nucléaire" },
    { "expr": "rte_hydraulique", "legendFormat": "Hydraulique" },
    { "expr": "rte_solaire", "legendFormat": "Solaire" },
    { "expr": "rte_eolien", "legendFormat": "Éolien" },
    { "expr": "rte_charbon", "legendFormat": "Charbon" },
    { "expr": "rte_gaz", "legendFormat": "Gaz" }
   ]
  },
  {
   "title": "CO2/KW",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "massg" } },
   "targets": [
    { "expr": "rte_taux_co2", "legendFormat": "Co2/KW" }
   ]
  },
  {
   "title": "MIX ENERGETIQUE",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 7, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "rte_fioul/rte_consommation", "legendFormat": "Fioul" },
    {
     "expr": "rte_bioenergies/rte_consommation",
     "legendFormat": "Bio energies"
    },
    { "expr": "rte_nucleaire/rte_consommation", "legendFormat": "Nucléaire" },
    {
     "expr": "rte_hydraulique/rte_consommation",
     "legendFormat": "Hydraulique"
    },
    { "expr": "rte_solaire/rte_consommation", "legendFormat": "Solaire" },
    { "expr": "rte_eolien/rte_consommation", "legendFormat": "Éolien" },
    { "expr": "rte_charbon/rte_consommation", "legendFormat": "Charbon" },
    { "expr": "rte_gaz/rte_consommation", "legendFormat": "Gaz" }
   ]
  },
  {
   "title": "MIX ENERGETIQUE",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 13, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    { "expr": "rte_fioul/rte_consommation", "legendFormat": "Fioul" },
    {
     "expr": "rte_bioenergies/rte_consommation",
     "legendFormat": "Bio energies"
    },
    { "expr": "rte_nucleaire/rte_consommation", "legendFormat": "Nucléaire" },
    {
     "expr": "rte_hydraulique/rte_consommation",
     "legendFormat": "Hydraulique"
    },
    { "expr": "rte_solaire/rte_consommation", "legendFormat": "Solaire" },
    { "expr": "rte_eolien/rte_consommation", "legendFormat": "Éolien" },
    { "expr": "rte_charbon/rte_consommation", "legendFormat": "Charbon" },
    { "expr": "rte_gaz/rte_consommation", "legendFormat": "Gaz" }
   ]
  },
  {
   "title": "PREVISIONS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "targets": [
    { "expr": "rte_prevision_j", "legendFormat": "J" },
    { "expr": "rte_prevision_j1", "legendFormat": "J+1" },
    { "expr": "rte_consommation", "legendFormat": "ACTUEL" }
   ]
  },
  {
   "title": "MANQUE/SURPLUS PRODUCTION",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "targets": [
    {
     "expr": "(rte_fioul+rte_bioenergies+rte_nucleaire+rte_hydraulique+rte_solaire+rte_eolien+rte_charbon+rte_gaz)-rte_consommation",
     "legendFormat": "Manque/Surplus"
    }
   ]
  },
  {
   "title": "ECHANGES",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "megwatt" } },
   "targets": [
    {
     "expr": "rte_ech_comm_allemagne_belgique",
     "legendFormat": "AL/BE"
    },
    { "expr": "rte_ech_comm_espagne", "legendFormat": "ES" },
    { "expr": "rte_ech_comm_italie", "legendFormat": "IT" },
    { "expr": "rte_ech_comm_suisse", "legendFormat": "SW" },
    { "expr": "rte_ech_comm_angleterre", "legendFormat": "GB" }
   ]
  },
  {
   "title": "ECHANGES",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "megwatt" } },
   "targets": [
    { "expr": "rte_ech_physiques", "legendFormat": "TOTAL" }
   ]
  }
 ]
}